# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_fuzzyCmeansROIs <- function(peakMatrix, ROIs, numPeaks, numPixels, numClusters, m, maxIterations, epsilon, verbose) {
    .Call('_fcmR_C_fuzzyCmeansROIs', PACKAGE = 'fcmR', peakMatrix, ROIs, numPeaks, numPixels, numClusters, m, maxIterations, epsilon, verbose)
}

C_fuzzyCmeansRandom <- function(peakMatrix, numPeaks, numPixels, numClusters, m, maxIterations, epsilon, verbose) {
    .Call('_fcmR_C_fuzzyCmeansRandom', PACKAGE = 'fcmR', peakMatrix, numPeaks, numPixels, numClusters, m, maxIterations, epsilon, verbose)
}

